package tui

import (
	"strings"
	"testing"
	"time"

	"github.com/anutron/claude-command-center/internal/daemon"
	"github.com/anutron/claude-command-center/internal/db"
	"github.com/anutron/claude-command-center/internal/llm"
	"github.com/anutron/claude-command-center/internal/plugin"
	tea "github.com/charmbracelet/bubbletea"
)

// newTestModel creates a Model with standard dimensions ready for View() calls.
func newTestModel(t *testing.T) Model {
	t.Helper()
	cfg := testSetup(t)
	database, err := db.OpenDB(t.TempDir() + "/test.db")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { database.Close() })

	m := NewModel(database, cfg, plugin.NewBus(), plugin.NewMemoryLogger(), llm.NoopLLM{})
	m.width = 120
	m.height = 40
	return m
}

// assertViewContains fails with a view dump if text is not found in view.
func assertViewContains(t *testing.T, view, text string) {
	t.Helper()
	if !strings.Contains(view, text) {
		t.Errorf("expected view to contain %q, but it did not.\nFull view:\n%s", text, view)
	}
}

// assertViewNotContains fails with a view dump if text IS found in view.
func assertViewNotContains(t *testing.T, view, text string) {
	t.Helper()
	if strings.Contains(view, text) {
		t.Errorf("expected view NOT to contain %q, but it did.\nFull view:\n%s", text, view)
	}
}

func TestView_PendingQuitShowsHint(t *testing.T) {
	m := newTestModel(t)

	// Before esc, no quit hint.
	v := m.View()
	assertViewNotContains(t, v, "Press esc again to quit")

	// Send first esc — the sessions plugin might consume it, so set pendingQuit directly
	// to test the view behavior in isolation.
	m.pendingQuit = true
	v = m.View()
	assertViewContains(t, v, "Press esc again to quit")
}

func TestView_DoubleEscQuitFlow(t *testing.T) {
	m := newTestModel(t)

	// First esc: the active plugin may handle it. If not, pendingQuit is set.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyEsc})
	m = result.(Model)

	// If plugin didn't consume it, pendingQuit should be true.
	// Some plugins consume esc at top level, so we force pendingQuit for the test.
	m.pendingQuit = true

	// Second esc within timeout should return tea.Quit.
	result, cmd := m.Update(tea.KeyMsg{Type: tea.KeyEsc})
	m = result.(Model)
	if cmd == nil {
		t.Error("expected tea.Quit command on second esc, got nil")
	}
}

func TestView_TabRoutesSendTabViewMsg(t *testing.T) {
	m := newTestModel(t)

	// Initial tab is tabCommand (0). Tab forward.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyTab})
	m = result.(Model)

	// Should advance to next tab.
	if m.activeTab == tabCommand {
		t.Errorf("expected tab to advance past tabCommand after Tab key")
	}

	// View should render without panic and show tab bar.
	v := m.View()
	if v == "" {
		t.Error("expected non-empty view after tab switch")
	}
}

func TestView_TabBarShowsAllLabels(t *testing.T) {
	m := newTestModel(t)
	v := m.View()

	// After consolidation, the tab bar shows "Sessions" as a single entry
	// (not "Active", "New Session", "Resume" separately).
	assertViewContains(t, v, "Sessions")
	assertViewContains(t, v, "Command Center")
	assertViewContains(t, v, "Settings")
}

func TestView_TabBarDoesNotShowOldSessionLabels(t *testing.T) {
	m := newTestModel(t)
	v := m.View()

	// The old separate tab labels should NOT appear in the host tab bar.
	// "Sessions" replaces "Active", "New Session", and "Resume".
	// Note: "New Session" may appear inside the sessions plugin's sub-tab bar,
	// but NOT in the host-level tab bar. We check the tab bar region specifically.
	// Since the host tab bar is rendered before plugin content, we check that
	// "Active" and "Resume" don't appear as top-level tab labels.
	// The host tab bar should only contain: Command Center, Sessions, PRs, Settings.
	assertViewNotContains(t, v, "> Active")
	assertViewNotContains(t, v, "> Resume")
}

func TestView_BannerVisibleByDefault(t *testing.T) {
	m := newTestModel(t)
	v := m.View()

	// The banner renders block art for the config name "Test Center".
	// The block font renders "TEST CENTER" in uppercase block chars.
	// The subtitle is generated by subtitleFromText if configured.
	// At minimum, the banner produces block characters with Unicode box drawing.
	if !strings.Contains(v, "█") {
		t.Error("expected banner block art characters in view when banner is visible")
	}
}

func TestView_BannerHiddenWhenConfigured(t *testing.T) {
	m := newTestModel(t)
	m.cfg.SetShowBanner(false)

	v := m.View()

	// With banner hidden, there should be no block art characters.
	// The tab bar and plugin content should still render.
	if strings.Contains(v, "█") {
		t.Error("expected no banner block art when banner is hidden")
	}
	// Tab bar should still be present.
	assertViewContains(t, v, "Sessions")
}

func TestView_WindowResizePropagates(t *testing.T) {
	m := newTestModel(t)

	result, _ := m.Update(tea.WindowSizeMsg{Width: 80, Height: 30})
	m = result.(Model)

	if m.width != 80 {
		t.Errorf("expected width=80, got %d", m.width)
	}
	if m.height != 30 {
		t.Errorf("expected height=30, got %d", m.height)
	}

	// View should produce non-empty output at the new size.
	v := m.View()
	if v == "" {
		t.Error("expected non-empty view after resize")
	}
}

func TestView_ActiveTabIndicator(t *testing.T) {
	m := newTestModel(t)

	// Tab bar should contain all tab labels.
	v := m.View()
	assertViewContains(t, v, "Sessions")
	assertViewContains(t, v, "Command Center")

	// Switch active tab — view should still render correctly.
	m.activeTab = tabCommand
	v = m.View()
	assertViewContains(t, v, "Command Center")
}

func TestView_NonEscKeyCancelsPendingQuit(t *testing.T) {
	m := newTestModel(t)
	m.pendingQuit = true

	// Any non-esc key should cancel pendingQuit.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'a'}})
	m = result.(Model)

	if m.pendingQuit {
		t.Error("expected pendingQuit to be cancelled after non-esc key")
	}

	v := m.View()
	assertViewNotContains(t, v, "Press esc again to quit")
}

func TestView_ShiftTabNavigatesBackward(t *testing.T) {
	m := newTestModel(t)

	// From tab 0, shift-tab should wrap to last tab (Settings).
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyShiftTab})
	m = result.(Model)

	if int(m.activeTab) != len(m.tabs)-1 {
		t.Errorf("expected last tab after shift-tab from first, got %d", m.activeTab)
	}

	v := m.View()
	assertViewContains(t, v, "> Settings")
}

func TestView_EmptyDimensionsProducesOutput(t *testing.T) {
	m := newTestModel(t)
	m.width = 0
	m.height = 0

	// View() should not panic and should still produce output,
	// just without the lipgloss.Place centering wrapper.
	v := m.View()
	if v == "" {
		t.Error("expected non-empty view even with zero dimensions")
	}
}

func TestView_BudgetWidgetNormal(t *testing.T) {
	m := newTestModel(t)
	// No daemonConn — should show "not running".
	m.daemonConn = nil
	v := m.View()
	assertViewContains(t, v, "not running")
}

func TestView_BudgetWidgetConnectedShowsSpend(t *testing.T) {
	m := newTestModel(t)
	dc := &DaemonConn{}
	dc.connected.Store(true)
	m.daemonConn = dc
	m.budgetAvailable = true
	m.budgetStatus = daemon.BudgetStatusResult{
		HourlySpent:  5.00,
		HourlyLimit:  20.00,
		ActiveAgents: 0,
	}
	v := m.View()
	assertViewContains(t, v, "$5.00")
	assertViewContains(t, v, "$20")
}

func TestView_BudgetWidgetWarningLevel(t *testing.T) {
	m := newTestModel(t)
	dc := &DaemonConn{}
	dc.connected.Store(true)
	m.daemonConn = dc
	m.budgetAvailable = true
	m.budgetStatus = daemon.BudgetStatusResult{
		HourlySpent:  17.00,
		HourlyLimit:  20.00,
		ActiveAgents: 0,
		WarningLevel: "warning",
	}
	v := m.View()
	assertViewContains(t, v, "$17.00")
}

func TestView_BudgetWidgetCriticalLevel(t *testing.T) {
	m := newTestModel(t)
	dc := &DaemonConn{}
	dc.connected.Store(true)
	m.daemonConn = dc
	m.budgetAvailable = true
	m.budgetStatus = daemon.BudgetStatusResult{
		HourlySpent:  19.50,
		HourlyLimit:  20.00,
		ActiveAgents: 0,
		WarningLevel: "critical",
	}
	v := m.View()
	assertViewContains(t, v, "CRITICAL")
}

func TestView_BudgetWidgetEmergencyStop(t *testing.T) {
	m := newTestModel(t)
	dc := &DaemonConn{}
	dc.connected.Store(true)
	m.daemonConn = dc
	m.budgetAvailable = true
	m.budgetStatus = daemon.BudgetStatusResult{
		EmergencyStopped: true,
	}
	v := m.View()
	assertViewContains(t, v, "EMERGENCY STOP")
}

func TestView_BudgetWidgetAgentCount(t *testing.T) {
	m := newTestModel(t)
	dc := &DaemonConn{}
	dc.connected.Store(true)
	m.daemonConn = dc
	m.budgetAvailable = true
	m.budgetStatus = daemon.BudgetStatusResult{
		HourlySpent:  5.00,
		HourlyLimit:  20.00,
		ActiveAgents: 3,
	}
	v := m.View()
	assertViewContains(t, v, "3 agents")
}

func TestView_ConsoleOverlay_TildeToggles(t *testing.T) {
	m := newTestModel(t)

	// Console is hidden by default.
	if m.console.visible {
		t.Fatal("console should start hidden")
	}

	// Tilde key should open the overlay.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'~'}})
	m = result.(Model)

	if !m.console.visible {
		t.Error("expected console overlay to be visible after ~ key")
	}

	// View should render the overlay title.
	v := m.View()
	assertViewContains(t, v, overlayTitle)

	// Tilde again should close the overlay.
	result, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'~'}})
	m = result.(Model)

	if m.console.visible {
		t.Error("expected console overlay to be hidden after second ~ key")
	}
}

func TestView_ConsoleOverlay_EscCloses(t *testing.T) {
	m := newTestModel(t)

	// Open overlay by setting state directly.
	m.console.visible = true
	m.console.entries = nil

	v := m.View()
	assertViewContains(t, v, overlayTitle)

	// Esc should close the overlay.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'~'}})
	m = result.(Model)
	// Second ~ closes it
	if m.console.visible {
		// Was opened then closed
	}
	// Set directly and test esc
	m.console.visible = true
	result, _ = m.Update(tea.KeyMsg{Type: tea.KeyEsc})
	m = result.(Model)

	if m.console.visible {
		t.Error("expected console overlay to be hidden after esc key")
	}
}

func TestView_ConsoleOverlay_ShowsEmptyState(t *testing.T) {
	m := newTestModel(t)

	// Open with no entries.
	m.console.visible = true
	m.console.entries = nil

	v := m.View()
	assertViewContains(t, v, overlayTitle)
	assertViewContains(t, v, overlayEmpty)
}

func TestView_ConsoleOverlay_ShowsEntries(t *testing.T) {
	m := newTestModel(t)

	entries := []db.AgentHistoryEntry{
		{
			AgentID:     "agent001",
			Status:      "completed",
			OriginLabel: "TODO #55 — Test entry",
			OriginRef:   "todo:55",
			DurationSec: 60,
			CostUSD:     0.005,
		},
	}
	m.console.visible = true
	m.console.entries = entries

	v := m.View()
	assertViewContains(t, v, overlayTitle)
	assertViewContains(t, v, "TODO #55")
}

func TestView_ConsoleOverlay_TildeSkippedWhenPluginConsumes(t *testing.T) {
	m := newTestModel(t)

	// Console starts hidden.
	if m.console.visible {
		t.Fatal("console should start hidden")
	}

	// Replace the active plugin with a fake that consumes all keys.
	// This simulates a plugin in text-input mode (editing a todo title, etc.).
	fake := &fakeConsumingPlugin{}
	m.tabs[m.activeTab].plugin = fake

	// Send ~ key — the plugin should consume it and the console should NOT open.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'~'}})
	m = result.(Model)

	if m.console.visible {
		t.Error("expected console overlay to NOT open when active plugin consumes ~ key")
	}
}

// fakeConsumingPlugin always returns ActionConsumed for HandleKey, simulating
// a plugin in text-input mode where all keys are consumed by the input field.
type fakeConsumingPlugin struct{ stubPlugin }

func (f *fakeConsumingPlugin) HandleKey(msg tea.KeyMsg) plugin.Action {
	return plugin.ConsumedAction()
}

// fakeWidePlugin returns content wider than ContentMaxWidth, simulating a
// plugin with long data rows (e.g., session list with full paths).
type fakeWidePlugin struct{ stubPlugin }

func (f *fakeWidePlugin) View(width, height, frame int) string {
	// Return a line that's 200 chars wide — wider than ContentMaxWidth (120).
	return strings.Repeat("X", 200)
}

func TestView_BUG127_BannerStableWithWidePluginContent(t *testing.T) {
	m := newTestModel(t)
	m.width = 160
	m.height = 40

	// Record the banner position with a normal-width plugin (tab 0).
	m.activeTab = 0
	v1 := m.View()
	bannerMargin1 := findBannerMargin(t, v1)

	// Replace one tab's plugin with a wide-content plugin and switch to it.
	wideTab := tab(len(m.tabs) - 2) // second-to-last tab (before Settings)
	m.tabs[wideTab].plugin = &fakeWidePlugin{}
	m.activeTab = wideTab
	v2 := m.View()
	bannerMargin2 := findBannerMargin(t, v2)

	if bannerMargin1 != bannerMargin2 {
		t.Errorf("BUG-127: banner margin shifted from %d to %d when switching to wide-content plugin",
			bannerMargin1, bannerMargin2)
	}
}

// findBannerMargin returns the left margin (leading spaces) of the first
// banner line (containing block art characters) in the rendered view.
func findBannerMargin(t *testing.T, view string) int {
	t.Helper()
	for _, line := range strings.Split(view, "\n") {
		if strings.Contains(line, "\u2588") { // █ block char
			trimmed := strings.TrimLeft(line, " ")
			return len(line) - len(trimmed)
		}
	}
	t.Fatal("BUG-127: could not find banner block art in view")
	return 0
}

func TestView_ConsoleOverlay_ConsumesKeysWhileOpen(t *testing.T) {
	m := newTestModel(t)
	m.console.visible = true
	m.console.entries = nil

	// 'a' key should be consumed (not passed to plugin).
	// The overlay should remain visible (no crash, no state change).
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'a'}})
	m = result.(Model)

	if !m.console.visible {
		t.Error("expected overlay to remain visible after non-navigation key")
	}
}

func TestView_ConsoleOverlay_LLMActivity(t *testing.T) {
	m := newTestModel(t)
	m.console.visible = true
	m.console.entries = nil // no agents

	now := time.Now()
	m.console.llmActivity = []daemon.LLMActivityEvent{
		{
			ID:        "llm-1",
			Operation: "command",
			Source:    "commandcenter",
			StartedAt: now.Add(-12 * time.Second),
			Status:    "running",
		},
		{
			ID:        "llm-2",
			Operation: "focus",
			Source:    "commandcenter",
			StartedAt: now.Add(-5 * time.Second),
			Status:    "completed",
		},
	}

	v := m.View()
	assertViewContains(t, v, "llm activity")
	assertViewContains(t, v, "command")
	assertViewContains(t, v, "focus")
}

func TestView_ConsoleOverlay_NoLLMActivity(t *testing.T) {
	m := newTestModel(t)
	m.console.visible = true
	m.console.entries = nil
	m.console.llmActivity = nil

	v := m.View()
	if strings.Contains(v, "llm activity") {
		t.Error("should not show 'llm activity' section when no LLM entries")
	}
}

func TestView_HelpOverlay_QuestionMarkShowsHelp(t *testing.T) {
	m := newTestModel(t)

	// Ensure we're on the command center tab.
	if m.activeTab != tabCommand {
		t.Fatal("expected initial tab to be command center")
	}

	// Before pressing ?, the view should NOT show the help overlay.
	v := m.View()
	assertViewNotContains(t, v, "KEYBOARD SHORTCUTS")

	// Send ? key through the full TUI Update path.
	result, _ := m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'?'}})
	m = result.(Model)

	// The view should now show the help overlay.
	v = m.View()
	assertViewContains(t, v, "KEYBOARD SHORTCUTS")
	assertViewContains(t, v, "Toggle this help")

	// Pressing any key should dismiss the overlay and show the command center again.
	result, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'q'}})
	m = result.(Model)
	v = m.View()
	assertViewNotContains(t, v, "KEYBOARD SHORTCUTS")
}

func TestView_HelpOverlay_WideTerminalNotClipped(t *testing.T) {
	m := newTestModel(t)

	// Simulate a wide terminal (wider than ContentMaxWidth).
	result, _ := m.Update(tea.WindowSizeMsg{Width: 200, Height: 50})
	m = result.(Model)

	// Open help overlay.
	result, _ = m.Update(tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune{'?'}})
	m = result.(Model)

	v := m.View()
	assertViewContains(t, v, "KEYBOARD SHORTCUTS")
	// The right border must not be clipped by MaxWidth truncation.
	assertViewContains(t, v, "╰")
	assertViewContains(t, v, "╮")
	// Descriptions must not be truncated.
	assertViewContains(t, v, "Cycle expanded view (2-col / 1-col / collapse)")
}
